apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 30d
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: alertmanager-data
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi
